### ISSUE TITLE
eRROR:device_event_log_impl.cc(215)] [08:24:57.430] Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.

### ISSUE THREAD

**Issue by richardwillramos** [lucasfdelis/Google-Maps-Crawler#1]
Oi, consegue me ajudar?

Depois de rodar a aplicação, ela abre seleciona a planilha e abre a janela do chrome. Não faz mais nada a partir desse ponto. No console é mostrado o erro eRROR:device_event_log_impl.cc(215)] [08:24:57.430] Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed. 

Entendo quase nada de python e não sei como resolver isso. Consegue me ajudar? Meu whats é 41 992178734

**Comment by lucasfdelis** [comment]
Boa noite! 

Segue em anexo um vídeo explicando a utilização do programa.

Lembrando que a planilha selecionada no início deve estar vazia, pois ela que recebe os dados coletados.

Qualquer dúvida estou a disposição.

https://user-images.githubusercontent.com/39414546/204116562-4601fb4e-f718-4c57-a42c-a28af7acaaa5.mp4
